apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: frontend-destination-rule
spec:
  host: frontend
  subsets:
    - name: v1
      labels:
        version: v0.1.2
    - name: v2
      labels:
        version: v0.1.3
  # trafficPolicy:
  # loadBalancer:
  #   simple: RANDOM
